import React, { useState, useMemo } from 'react';
import { ArrowLeft, Search, FileText, AlertTriangle, ShieldCheck, CreditCard, Scale, HelpCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import './Terms.css';

const Terms = () => {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState('agreement'); // 'agreement' | 'partA' | 'partB'
  const [searchQuery, setSearchQuery] = useState('');

  // Sections data to facilitate search and structured rendering
  const sections = useMemo(() => [
    {
      id: 'agreement',
      title: 'User Agreement',
      category: 'agreement',
      content: [
        {
          heading: 'Introduction & Preamble',
          text: `This Terms and Conditions and User Agreement ("Agreement") constitutes a legally binding contract between M/s AGRIFATHER, a partnership firm established under the Indian Partnership Act, 1932, and the user ("User", "You", "Your") accessing or utilizing the digital platform, applications, and services available at www.agrifather.com and its corresponding Progressive Web Application (PWA).`
        },
        {
          heading: 'Acceptance of Terms',
          text: `By registering an account, ticking the "I Agree" checkbox, or interacting with any feature of the platform, you acknowledge that you have read, understood, and voluntarily agreed to be bound by these terms. If you do not agree to these provisions, you must immediately cease all use of the platform and its services.`
        },
        {
          heading: 'Review and Confirmation',
          text: `You are requested to review the enclosed drafts and indicate if any commercial, operational, or functional changes are required. Upon confirmation, the same may be formally published on the Platform.`
        }
      ]
    },
    {
      id: 'partA',
      title: 'Part A: Business-Wide Terms',
      category: 'partA',
      content: [
        {
          num: 1,
          heading: 'Statutory and Regulatory Compliance Framework',
          text: `These Terms are formulated, published, and maintained in strict adherence to the prevailing legal and regulatory landscape of India. This electronic record is generated by a computer system and does not require physical or digital signatures when accepted electronically. This framework operates in direct alignment with:\n\n★ The Information Technology Act, 2000 (and its subsequent amendments);\n★ The Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021;\n★ The Digital Personal Data Protection (DPDP) Act, 2023, wherein the Firm operates as a "Data Fiduciary";\n★ The Consumer Protection Act, 2019 and the rules framed thereunder for e-commerce and digital services.\n\nThis Agreement replaces all prior communications and ensures that the platform maintains its statutory safe harbor protections under Section 79 of the Information Technology Act, 2000.`
        },
        {
          num: 2,
          heading: 'Eligibility, Age Competency, and User Representations',
          text: `By utilizing the platform, you represent and warrant that you are at least eighteen (18) years of age and possess the complete legal capacity to enter into a binding, enforceable contract under the Indian Contract Act, 1872. The platform is targeted primarily at Indian farmers, small-scale agricultural stakeholders, and enthusiasts. While agricultural data may be browsed by individuals between the ages of thirteen (13) and seventeen (17), full account registration, localized scanning, and paid subscription features require the user to be 18 years or older. The platform does not knowingly collect or verify the personal data of unaccompanied minors for core features without parental guidance. You further represent that all information provided during registration—including names, email addresses, and mobile numbers—is accurate, current, and truthful.`
        },
        {
          num: 3,
          heading: 'Intellectual Property Rights and Licensing',
          text: `All original content available on the platform—including but not limited to text, UI designs, graphics, source code, backend Node.js architectures, React components, MERN-stack system flows, layouts, and corporate logos—is the exclusive intellectual property of the Firm and is protected by the Copyright Act, 1957 and trademark laws of India.\n\nNo right, title, or interest is transferred to the User, except for a limited, revocable, non-transferable, and non-exclusive license to access and use the platform for personal, non-commercial, agricultural use. Users retain ownership of their raw inputs, uploaded crop images, and commentary; however, by uploading or submitting data onto the platform, you grant AgriFather a worldwide, royalty-free, perpetual, and sublicensable license to host, display, translate, and process such data to execute the software features and improve platform models.`
        },
        {
          num: 4,
          heading: 'Suspension, Account Termination, and Force Majeure',
          text: `The Firm reserves the right, at its sole discretion, to suspend, restrict, or permanently terminate user accounts and platform access without prior notice or liability if a user is found to be in violation of this Agreement, the IT Act, 2000, or any applicable Indian law. Such termination shall not affect any accrued financial obligations or statutory rights accumulated prior to the date of termination.\n\nFurthermore, AgriFather shall not be held liable or responsible for any failure, degradation, or delay in platform performance resulting from events beyond its reasonable control, including but not limited to acts of God, natural disasters, cyber warfare, server hacks, telecommunication infrastructure failures, internet blackouts, or unexpected regulatory shutdowns of underlying third-party APIs.`
        },
        {
          num: 5,
          heading: 'Amendments, Governing Law, and Jurisdiction',
          text: `AgriFather reserves the right to amend, alter, or modify this Agreement at any time by publishing the revised version directly on the platform website and application interface. Continued use of the platform following the publication of such updates constitutes your explicit and binding acceptance of the amended terms. This Agreement shall be governed by, construed, and enforced in accordance with the laws of the Republic of India. Any disputes, claims, or legal actions arising out of or relating to these Terms or the use of the digital application shall be subject to the exclusive jurisdiction of the competent courts located at New Delhi, India.`
        }
      ]
    },
    {
      id: 'partB',
      title: 'Part B: Product-Specific Terms & AI',
      category: 'partB',
      content: [
        {
          num: 6,
          heading: 'Nature of Agricultural Technology Services',
          text: `AgriFather operates an interactive, full-stack, Progressive Web Application (PWA) incorporating artificial intelligence, location-implied context, and market data modules. The platform features include text-based conversational interfaces ("AgriFather Bot"), computer-vision crop and disease scanning, dynamic and static market pricing indices ("Mandi Prices"), localized meteorological forecasting ("Weather Module"), soil and crop-stage recommendations ("Advisory Module"), automated pest identification, livestock tracking utilities, and a curated catalog of government agricultural assistance programs. The Company reserves the complete right to alter, modify, restrict, or discontinue any feature, admin panel configuration, or daily operational metric without prior notice.`
        },
        {
          num: 7,
          heading: 'Intermediary Status, Third-Party Content, and API Dependencies',
          text: `For specific operational modules, AgriFather functions strictly as an "intermediary" as defined under Section 2(1)(w) of the Information Technology Act, 2000. The Company does not introduce, select, modify, or validate information fetched via external, public APIs, such as real-time market data or regional weather forecasts. Consequently, the Company disclaims all liability for the accuracy, timeliness, or operational utility of third-party public API content. Furthermore, the core processing architecture relies on third-party AI frameworks via the OpenRouter API (including Nvidia, Llama, Gemma, and Mistral models). Because these are external, free-tier or variable third-party systems, the platform cannot guarantee an uptime Service Level Agreement (SLA) or ensure consistent response quality. Paid subscribers acknowledge that AI responses are delivered on a "best effort" basis.`
        },
        {
          num: 8,
          heading: 'Mandatory AI-Generated Content and Advisory Disclaimer',
          isCritical: true,
          text: `CRITICAL NOTICE TO ALL USERS: All insights, conversational answers, disease identifications, treatment suggestions, pest assessments, and mathematical evaluations generated by the AgriFather Bot or the Crop Scan module are automated, probabilistic outputs driven by artificial intelligence. They are provided for general educational and informational purposes only. Automated outputs do NOT constitute professional agronomic, chemical, veterinary, financial, or legally certified agricultural extension advice. Crop diseases, pest outbreaks, and soil variables differ significantly based on microscopic local environmental conditions that the AI cannot independently verify. Users are strictly warned NOT to implement critical farm management decisions, chemical allocations, or expensive crop treatments relying solely on the AI's recommendations. You must independently verify all AI-generated suggestions with certified local agronomists, Krishi Vigyan Kendras (KVKs), regional agricultural universities, or official government agricultural extension departments before executing any field changes. The platform explicitly disclaims any liability for financial losses, crop failures, livestock harm, or property damage resulting directly or indirectly from your reliance on the AI platform's conversational or analytical outputs.`
        },
        {
          num: 9,
          heading: 'Pricing Tiers, Subscription Model, and Refund Policy',
          isImportant: true,
          text: `The platform employs a structured "Freemium" business model segmented into distinct tiers of feature access:\n\n★ Free (Starter) Tier: Restricted to ten (10) standard text-based AI chat messages per day, basic crop advisory content, static market tables, and Hindi/English interface options. It explicitly excludes image-based disease scanning and multi-language AI token routing.\n\n★ Pro Paid Tiers: Available via paid commercial options priced at ₹399 per Month or ₹4,199 per Year (advertised values calculated in Indian currency denominations). Pro features unlock unlimited message loops, multi-language translation streams across ten (10) regional Indian languages, image-based crop disease scanners, livestock tracking, and priority support response lines.\n\nNO AUTO-RENEWAL NOTICE: All paid transactions executed on the platform are structured as one-time, fixed-duration purchases. The app's backend does not maintain auto-recurring merchant mandates or automated banking extraction systems. Upon expiration of your chosen 30-day or 365-day active term, your access level will automatically downgrade to the standard Starter Tier unless you manually execute a brand-new commercial purchase.\n\nREFUND POLICY: Due to the digital, instantaneous activation nature of information feeds and computational AI queries, the platform enforces a strict No-Refund Policy once a payment is successfully processed and verified. No pro-rata refunds, rollbacks, or cash returns will be entertained for voluntary account closures, unexpected third-party AI gateway gateway latency, or localized user network drops.`
        },
        {
          num: 10,
          heading: 'Razorpay Payment Gateway Integration',
          text: `All commercial payments, checkout processes, and financial transactions are routed securely through Razorpay, an external third-party payment aggregator complying with the Payment and Settlement Systems Act, 2007 and standard PCI-DSS specifications. When you click on a premium plan, the application initiates an order profile on the backend and loads the external Razorpay Checkout widget dynamically from checkout.razorpay.com. AgriFather does not directly collect, process, or store credit card numbers, net banking passwords, or private UPI authorization pins on its internal database infrastructure. Your payment details are governed directly by Razorpay's independent terms of service and data management frameworks. The platform becomes liable to unlock premium features only upon the successful programmatic return of authenticated transaction signatures and active confirmation logs from Razorpay's servers.`
        },
        {
          num: 11,
          heading: 'User Conduct, Security, and Prohibited System Uses',
          text: `Users must navigate the platform ethically and maintain the strict security of their access routes. Accessing restricted operational sections or the comment system requires an active user profile authenticated via mobile-based One-Time Passwords (OTP). You are entirely responsible for preventing unauthorized parties from utilizing your active session state on your device. The following actions are strictly prohibited on the platform:\n\n★ Deploying data scrapers, automated spiders, reverse-engineering scripts, or executing mass extraction tools to siphon off the platform's proprietary code, blog text, or curated database models;\n★ Bypassing backend validation checks or injection systems to transmit non-agricultural queries, malicious software payloads, or dangerous script executions into the Express/NodeJS server network;\n★ Uploading corrupt images, biometric files, or explicit graphics exceeding the maximum single file allocation limit of 10 Megabytes (10MB);\n★ Using the platform's comments or feedback channels to spread hate speech, defamatory language, or unverified market rumors in violation of Rule 3 of the IT Intermediary Rules, 2021.`
        },
        {
          num: 12,
          heading: 'Limitation of Liability and Indemnity',
          text: `To the maximum extent permitted by applicable Indian jurisprudence, the total aggregate liability of AgriFather, its founding partners, advocates, and internal research associates for any civil claim, negligence lawsuit, contractual dispute, or statutory violation shall be strictly capped at the exact amount paid by the user for their premium subscription tier during the active billing period in question. In no event shall the Firm or its associates be held liable for any indirect, incidental, consequential, special, or exemplary damages—including but not limited to loss of crop yield, loss of business revenue, anticipated agricultural profits, or land valuation drops—arising out of the use, performance, or inability to use the interactive AI engine. You agree to indemnify, defend, and hold harmless AgriFather and its operational team from any third-party claims, legal losses, court costs, or damages arising from your malicious misuse of the platform or your direct breach of the terms of this Agreement.`
        },
        {
          num: 13,
          heading: 'Statutory Grievance Redressal Mechanism',
          text: `In strict compliance with Rule 3(2) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, any user facing service disruptions, systemic privacy breaches, or seeking to report illegal user-generated content may contact the designated Grievance Officer:\n\n★ Name of Grievance Officer: Shri Chetan Rathi\n★ Corporate Entity: M/s AGRIFATHER\n★ Official Communication Email: support@agrifather.com\n\nThe Grievance Officer shall formally acknowledge your complaint within forty-eight (48) hours of receipt and provide a resolution or definitive response within fifteen (15) days in accordance with the timelines mandated under prevailing Indian digital intermediary statutes.`
        }
      ]
    }
  ], []);

  // Utility to highlight search keywords
  const highlightText = (text, query) => {
    if (!query) return text;
    const parts = text.split(new RegExp(`(${query.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&')})`, 'gi'));
    return (
      <>
        {parts.map((part, i) => 
          part.toLowerCase() === query.toLowerCase() 
            ? <span key={i} className="highlighted-text">{part}</span> 
            : part
        )}
      </>
    );
  };

  // Filter sections and items based on search query
  const filteredSections = useMemo(() => {
    if (!searchQuery) {
      return sections.filter(s => s.id === activeTab);
    }
    const query = searchQuery.toLowerCase();
    
    // Search across all sections if there is a query, and return matching headings or texts
    const results = [];
    sections.forEach(section => {
      const matchingItems = section.content.filter(
        item => item.heading.toLowerCase().includes(query) || item.text.toLowerCase().includes(query)
      );
      if (matchingItems.length > 0) {
        results.push({
          ...section,
          content: matchingItems
        });
      }
    });
    return results;
  }, [sections, activeTab, searchQuery]);

  return (
    <div className="terms-page">
      {/* Header */}
      <div className="terms-header">
        <button className="back-btn" onClick={() => navigate(-1)} aria-label="Go Back">
          <ArrowLeft size={24} />
        </button>
        <div className="header-title-section">
          <h2>Terms & Conditions</h2>
          <p className="subtitle">User Agreement & Disclaimers</p>
        </div>
      </div>

      <div className="terms-container">
        {/* Search Bar */}
        <div className="search-box-wrapper">
          <Search size={18} className="search-icon" />
          <input
            type="text"
            placeholder="Search terms, policies, or disclaimers..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="terms-search-input"
          />
          {searchQuery && (
            <button className="clear-search-btn" onClick={() => setSearchQuery('')}>×</button>
          )}
        </div>

        {/* Tab navigation (hidden when searching) */}
        {!searchQuery && (
          <div className="terms-tabs">
            <button
              className={`tab-btn ${activeTab === 'agreement' ? 'active' : ''}`}
              onClick={() => setActiveTab('agreement')}
            >
              <FileText size={16} />
              <span>User Agreement</span>
            </button>
            <button
              className={`tab-btn ${activeTab === 'partA' ? 'active' : ''}`}
              onClick={() => setActiveTab('partA')}
            >
              <Scale size={16} />
              <span>Part A: Business Terms</span>
            </button>
            <button
              className={`tab-btn ${activeTab === 'partB' ? 'active' : ''}`}
              onClick={() => setActiveTab('partB')}
            >
              <AlertTriangle size={16} />
              <span>Part B: Product & AI</span>
            </button>
          </div>
        )}

        {/* Legal Text content list */}
        <div className="terms-content-area">
          {searchQuery && (
            <div className="search-results-info">
              Showing search results for "{searchQuery}":
            </div>
          )}
          
          {filteredSections.length === 0 ? (
            <div className="no-results-card">
              <HelpCircle size={40} className="no-results-icon" />
              <p>No matching sections found. Please try a different query.</p>
            </div>
          ) : (
            filteredSections.map((section) => (
              <div key={section.id} className="terms-section-block">
                {searchQuery && <h3 className="section-group-title">{section.title}</h3>}
                
                {section.content.map((item, idx) => {
                  let cardClass = "terms-item-card";
                  let Icon = FileText;
                  
                  if (item.isCritical) {
                    cardClass += " critical-card";
                    Icon = AlertTriangle;
                  } else if (item.isImportant) {
                    cardClass += " important-card";
                    Icon = CreditCard;
                  } else if (item.num === 2) {
                    Icon = ShieldCheck;
                  } else if (item.num === 6 || item.num === 13) {
                    Icon = Scale;
                  }

                  return (
                    <div key={idx} className={cardClass}>
                      <div className="card-header-row">
                        <div className="icon-badge">
                          <Icon size={18} />
                        </div>
                        <h4 className="item-heading">
                          {item.num ? `${item.num}. ` : ''}
                          {highlightText(item.heading, searchQuery)}
                        </h4>
                      </div>
                      <div className="item-body-text">
                        {highlightText(item.text, searchQuery).split('\n').map((paragraph, pIdx) => (
                          <p key={pIdx}>{paragraph}</p>
                        ))}
                      </div>
                    </div>
                  );
                })}
              </div>
            ))
          )}
        </div>
      </div>

      <div className="terms-footer-note">
        <p>© 2026 M/s AGRIFATHER. All Rights Reserved.</p>
        <p>Principal Place of Business: Sector 14, Dwarka, New Delhi-110078</p>
      </div>
    </div>
  );
};

export default Terms;
